### ISSUE TITLE
[feat] Customizable Controls

### ISSUE THREAD

**Issue by aqilc** [kbz/kbz.github.io#9]
This is unplayable because the default controls are really weird and I can't even change them. I don't think anyone is down to learn your specific keyboard controls just to practice finesse.

**Comment by kbz** [comment]
Did you try clicking the cog icon on the top left corner of the screen? You can customize almost all of the game settings including bindings and whatnot.

To assign new bindings, just click the cell of the binding you want to change and press the new binding.

**Comment by aqilc** [comment]
Oh sorry I'm mentally disabled, I did not ever see that settings icon. I ctrl+fed for `control` and nothing popped up in that wall of text so I assumed there was nothing.
